# These are supported funding model platforms

github: Ajay-Dhangar

open_collective: twitter-bio # Replace with a single Open Collective username

custom: 'https://www.paypal.com/paypalme/ajzerocoding', 'https://topmate.io/ajay_dhangar' # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
